GLOBAL_APP_NAME = "StockTracker Pro"
GLOBAL_VERSION = "1.0.0"

API_RATE_LIMIT_CALLS = 5
API_RATE_LIMIT_PERIOD_SEC = 60

YFINANCE_DEFAULT_PERIOD = "1mo"
YFINANCE_DEFAULT_INTERVAL = "1d"

GEMINI_MODEL_NAME = "models/gemini-2.0-flash-lite"
GEMINI_MAX_TOKENS = 256
GEMINI_TEMPERATURE = 0.3

COLOR_BULLISH = "#10B981"
COLOR_BEARISH = "#EF4444"
COLOR_NEUTRAL = "#F59E0B"
COLOR_BG_PRIMARY = "#0A192F"
COLOR_BG_SECONDARY = "#112240"
COLOR_TEXT_PRIMARY = "#CCD6F6"
COLOR_TEXT_SECONDARY = "#8892B0"

TECHNICAL_SMA_WINDOWS = [20, 50, 200]
TECHNICAL_RSI_WINDOW = 14
TECHNICAL_MACD_FAST = 12
TECHNICAL_MACD_SLOW = 26
TECHNICAL_MACD_SIGNAL = 9

CONSENSUS_BULLISH_THRESHOLD = 0.2
CONSENSUS_BEARISH_THRESHOLD = -0.2

SEBI_DISCLAIMER = ("Disclaimer: StockTracker Pro is for educational purposes only. "
                   "Data may be delayed. Not registered with SEBI.")
